# Generated by Django 4.2.7 on 2025-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ultrasound", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("receptionist", "Receptionist"),
                ],
                default="patient",
                max_length=15,
            ),
        ),
    ]
