# Generated by Django 4.2.7 on 2025-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ultrasound", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="ultrasoundreport",
            name="status",
            field=models.CharField(
                choices=[("ready", "Ready"), ("printed", "Printed")],
                default="ready",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ultrasoundreport",
            name="signature",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
